// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    var delete_existing_entry;
    $("#virus_form").on('submit', function(e) {
      e.preventDefault();
      $("#virus_form_submit").attr('disabled', true);
      $.ajax({
        url: "http://localhost:8000/api/v1/virus",
        data: {
          entry_id: $("#id_entry_id").val(),
          format: 'json'
        },
        dataType: 'json',
        success: function(data) {
          var confirm_delete;
          confirm_delete = true;
          if (data.objects.length > 0) {
            confirm_delete = confirm("Virus exists already, continuing will delete the existing entry!");
            if (confirm) {
              return delete_existing_entry(data.objects[0].entry_id);
            }
          } else {
            return e.currentTarget.submit();
          }
        },
        error: function() {
          return alert('omg');
        }
      });
      return false;
    });
    return delete_existing_entry = function(entry_id) {
      return $.ajax({
        url: "/admin/add_entry/delete_entry",
        data: {
          entry_id: entry_id
        }
      }).done(function() {
        return $("#virus_form").submit();
      });
    };
  });

}).call(this);
