// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var prefill_info;
    prefill_info = function(entry_key) {
      $.ajax({
        url: "http://localhost:8000/api/v1/polymer",
        data: {
          entry_key: entry_key,
          format: 'json'
        },
        success: function(data) {
          return $.each(data.objects, function(index, polymer) {
            var hidden_input, input;
            input = $("<input></input>").attr({
              type: 'checkbox',
              name: 'entity_accession_id_' + index
            });
            hidden_input = $("<input></input>").attr({
              type: 'hidden',
              name: 'entity_accession_id',
              value: polymer.pdbx_db_accession
            });
            $(".js-polymers").append(input).append(hidden_input);
            return input.after($("<p></p>").html(polymer.pdbx_description));
          });
        },
        error: function(err) {
          return console.log(err);
        },
        dataType: 'json'
      });
      $.ajax({
        url: "http://localhost:8000/api/v1/struct",
        data: {
          entry_key: entry_key,
          format: 'json'
        },
        success: function(data) {
          var virus;
          virus = data.objects[0];
          $("#id_deposition_date").val(virus.entry_key.deposition_date);
          return $("#id_name").val(virus.title);
        },
        dataType: 'json'
      });
      return $("#virus_form").attr('hidden', false);
    };
    $('.formset').formset({
      prefix: '{{ layer_formset.prefix }}'
    });
    $("#id_unique").on('click', function() {
      return $("label[for=id_unique_relative_id], #id_unique_relative_id")[this.checked ? "hide" : "show"]();
    });
    return $.ajax({
      url: "http://localhost:8000/admin/add_entry/start_pdbase",
      data: {
        entry_id: $('#entry_id').attr("value"),
        format: 'json'
      },
      success: function(data) {
        prefill_info(data.entry_key);
        $("#virus_form").attr("hidden", !data.pdbase);
        return $(".message").attr("hidden", data.pdbase);
      },
      error: function(err) {
        return console.log(err);
      },
      dataType: 'json'
    });
  });

}).call(this);
