// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $("#virus_form_submit").on('click', function() {
      $.ajax({
        url: "http://localhost:8000/api/v1/virus",
        data: {
          entry_id: $("#id_entry_id").val(),
          format: 'json'
        },
        success: function(data) {
          var confirm_delete;
          confirm_delete = true;
          if (data.objects.length > 0) {
            confirm_delete = confirm("Virus exists already, continuing will delete the existing entry!");
          }
          if (confirm) {
            return $("#virus_form").submit();
          }
        },
        dataType: 'json'
      });
      return false;
    });
  });

}).call(this);
